### ISSUE TITLE
Hangup on NTSC VIC-IIs

### ISSUE THREAD

**Issue by laubzega** [Hojo-Norem/c0pperdragon-VIC-II-Palette-editor#1]
When trying to activate Colordore palette on either of NTSC VIC-IIs, the program gets to the screen visible on the photo and then hangs. Top monitor - S-Video, bottom - component (YCrCb).

![palette-hang](https://user-images.githubusercontent.com/5245003/84602105-e06f9780-ae39-11ea-8ec3-0eac15f796a8.jpeg)

**Comment by Hojo-Norem** [comment]
Ah.  It looks like some raster IRQ shenanigans...  I confirmed the behaviour in VICE set to NTSC.

I think I have it fixed.  I've uploaded a new version to the releases section.

**Comment by laubzega** [comment]
Yup, everything works fine now. Thank you!
