### ISSUE TITLE
Mod not working anymore

### ISSUE THREAD

**Issue by ei8htthepG** [Hojo-Norem/c0pperdragon-VIC-II-Palette-editor#6]
Hi,

my mod isn't working anymore. After I turn the c64 on there is just a weird picture on my BVM and no signal on a second monitor for test cases. The c64 displays a picture via S-Video. The chip on the mod is getting very hot (can't touch it after 5 seconds) shortly after I started the c64. I am a bit afraid. Can I check voltage somewere?

**Comment by Hojo-Norem** [comment]
Hi.  Sorry to hear that you are having trouble.  I suggest that you re-post your issue over at the the mod's repository:
https://github.com/c0pperdragon/C64-Video-Enhancement/issues

This repository if for the palette editor and I'm afraid that I can't really help you that much regarding the hardware.  c0pperdragon should have a better idea where to begin.  Posting a photo of the 'weird picture' that your BVM produces may help c0pperdragon narrow down the problem.
