### ISSUE TITLE
Changing color palette and saving to flash doesn't work with the latest firmware 2.10

### ISSUE THREAD

**Issue by jtompuri** [Hojo-Norem/c0pperdragon-VIC-II-Palette-editor#7]
I programmed the FPGA with the latest firmaware 2.10. The color palette defaulted to the original and I tried to change the color palette to Colodore. However, it seems that the colors in the editor doesn't change when I test them. Saving to flash and power cycling doesn't change the colors. The editor doesn't give any errors and saving to flash gives a feedback that the colors are now saved to flash.

**Comment by Hojo-Norem** [comment]
Hi.  Was the editor working on the older FPGA firmware?  I'll admit that I haven't tested the latest firmware myself as I've not personally had any need to upgrade from 2.6.

From a technical point of view, there no way to determine if palette operations are successful or not programmatically.

**Comment by jtompuri** [comment]
Yes, the editor v1.18 was working with the original 2.6 firmware. I tried both the latest editor v1.19 and v1.18. Test mode doesn’t change the colors either. Let me know, if I can somehow help to debug the issue.

**Comment by Hojo-Norem** [comment]
It looks like something might have broken in the later firmwares.  I'll see if I can dig out my USB Blaster and confirm the bug.  Chances are that the bug will need reporting to c0pperdragon.

**Comment by Hojo-Norem** [comment]
Okay.  Just uploaded the most recent firmware (C64mod_2_10.pof) and it seems to be operating correctly on my system.

Just to double check, are you remembering to toggle your video mode select switch when instructed to on the first screen of the editor?

**Comment by jtompuri** [comment]
Yes, it's working. I forgot to toggle the video mode select switch. Sorry about the inconvenience and thank you for your help. 🙏

**Comment by Hojo-Norem** [comment]
No problem.  Glad you got it working.
